# Generated by Django 5.1.2 on 2024-11-26 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('submissiondate', models.DateField(max_length=200)),
                ('studentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
                ('teachername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.teacher')),
            ],
        ),
    ]
