# Generated by Django 5.1.2 on 2024-12-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app1.homework')),
                ('studentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app1.student')),
            ],
        ),
    ]
